export default {
  translation: {
    walkthroughSlide1Title: 'Track your asset distribution',
    walkthroughSlide1Description: 'By adding the monetary value of your assets, you get pie charts out of the box.',
    walkthroughSlide2Title: 'See where your wealth is concentrated in',
    walkthroughSlide2Description: 'Group assets by categories to see the bigger picture of your net worth distribution',
    walkthroughSlide3Title: 'Follow your net worth performance',
    walkthroughSlide3Description: 'As you update asset values once per month, you get a history chart of your net worth, each category, and individual assets',
    walkthroughSlideLast: 'Getting started...',
    initialQuote: 'Know what you own, and know why you own it.',
    initialQuoteAuthor: 'Peter Lynch',
    dashboardTab: 'Dashboard',
    addAssetTab: 'Add Asset',
    addAssetHeader: 'Add Asset',
    addCategoryHeader: 'Add Category',
    updateExistingAssetsTab: 'Existing',
    updateExistingAssetsHeader: 'Update Existing Assets',
    addAssetButton: 'Add asset',
    assetName: 'Asset name',
    amount: 'Amount for {{month}}',
    category: 'Category',
    categoryListTitle: 'Asset Category',
    currency: 'Currency',
    currencyListTitle: 'Asset Currency',
    close: 'Close',
    saveAsset: 'Save asset',
    categories: {
      cash: 'Cash',
      stocks: 'Stocks',
      bonds: 'Bonds',
      p2pLending: 'P2P Lending'
    },
    addCategory: 'Add a category',
    save: 'Save',
    addCategoryRowText: 'Add a new category',
    confirmAddAssetMainText: 'Your asset is saved',
    confirmAddAssetDescriptionText: 'You can review it on the Dashboard',
    done: 'Done',
    assetChartTitle: 'Distribution by Assets',
    categoryChartTitle: 'Distribution by Category',
    assetByAbsoluteValueChartTitle: 'Asset Values',
    categoryByAbsoluteValueChartTitle: 'Category Values',
    netWorth: 'Total Net Worth',
    dashboardMonthSelectorTitle: 'Select month',
    outdatedAssetText: '(tap to update)',
    quickUpdateAssetTitle: 'Amount for {{month}}',
    moreOptions: 'More Options',
    currentAmount: 'Currently {{amount}}',
    addHistoricDataButton: 'Add historical data',
    deleteAmount: 'Delete month data',
    growth1m: '1m Growth',
    growth1y: '1y Growth',
    welcomeToNewMonthTitle: 'Welcome to {{month}}',
    welcomeToNewMonthMessage: 'Update your assets and see the new outlook of your net worth',
    errorFetchingData: 'Cannot connect to the server right now. The data displayed here may be outdated.',
    errorSavingData: 'There is a problem saving your data. Please try again later. ',
    months: '{{count}} month',
    months_plural: '{{count}} months',
    YTD: 'YTD',
    years: '{{count}} year',
    years_plural: '{{count}} years',
    max: 'Max',
    loginInstead: 'Login Instead',
    register: 'Register',
    emailAlreadyInUse: 'That email address is already in use!',
    invalidEmail: 'That email address is invalid!',
    invalidAccount: 'Invalid account!',
    passwordIncorrect: 'Password incorrect!',
    unableToAuthenticate: 'Unable to authenticate!',
    passwordWeak: 'The provided password is too weak!',
    logout: 'Sign-out',
    email: 'email',
    password: 'password',
    confirmPassword: 'confirm password',
    passwordsDoNotMatch: 'Passwords do not match!',
    registerInstead: 'Register Instead',
    profile: 'Profile',
    profileHeader: 'Profile',
    continueWithFacebook: 'Continue with Facebook',
    continueWithGoogle: 'Continue with Google',
    loginRegisterWithEmail: 'Login / Register with Email',
    useDifferentLoginMethod: 'Use a different login method',
    unableToLoginWithGoogle: 'Unable to login with Google right now',
    unableToLoginWithFacebook: 'Unable to login with Facebook right now',
    changeAssetName: 'Change asset title',
    addNewNameHere: 'Add the new name here',
    deleteAsset: 'Delete asset',
    deleteAssetForever: 'Delete {{assetName}} data forever?',
    yes: 'yes',
    baseCurrencyQuestion: 'Base Currency?',
    changeBaseCurrencyQuestion: "We've noticed you have assets in different currencies. Would you like to change your default base currency from {{baseCurrency}} to another one?",
    youCanAlwaysConfigure: 'You can always configure it later from your Profile settings.',
    keep: 'Keep {{baseCurrency}}',
    seeAvailableOptions: 'See Available Options',
    selectYourBaseCurrency: 'Select your base currency used to show your net worth in',
    selectYourBaseCurrencyLongDescription: 'Select your base currency. Your assets are still recorded in their original currency, and are converted to the base currency for calculation purposes (e.g. when showing your net worth or a specific category of assets).',
    baseCurrency: 'Base Currency',
    noDataPrior: 'No Data Prior to {{month}}',
    noPrevMonthAddHistoricalData: 'There is no asset data for a period earlier than {{month}}. You can see dashboard statistics once you add historical data. Would you like to do it now?',
    noThanks: 'No, thanks',
    addHistoricalData: 'Add Historical Datas',
    longTapToSeeDetails: 'Long tap on a pie slice to see details',
    assetRangeChartTitle: '{{asset}} value over time',
    assetRelativeToNetWorthRangeChartTitle: '{{asset}} % of your entire net worth over time',
    plusPercentagePoints: '{{text}} p.p.',
    rangeMessageTitle: 'Range Chart',
    rangeChartPlaceholderMessage: 'A range chart like this one will appear once you add future or historical data for assets.',
    addHistoricalDataNow: 'Add historical data now?',
    welcomeToNewMonthModalMessage: 'As it is a new month already, it is time to add new asset values. Charts will automatically be updated to reflect the new outlook of your net worth.',
    maybeLater: 'Maybe later',
    addDataFor: 'Add data for {{month}}',
    updateAssetValues: 'Update assets',
    singleAssetHeader: 'Update Single Asset',
    min6characters: '(min 6 characters)'
  }
};
