export default {
  translation: {
    initialQuote: 'Know what you own, and know why you own it.',
    initialQuoteAuthor: 'Peter Lynch',
    dashboardTab: 'Dashboard',
    addAssetTab: 'Add Asset',
    updateExistingAssetsTab: 'Existing',
    addAssetButton: 'Add asset',
    assetName: 'Asset name',
    amount: 'Amount for {{month}}',
    category: 'Category',
    categoryListTitle: 'Asset Category',
    currency: 'Currency',
    currencyListTitle: 'Asset Currency',
    close: 'Close',
    saveAsset: 'Save asset',
    categories: {
      cash: 'Cash',
      stocks: 'Stocks',
      bonds: 'Bonds',
      p2pLending: 'P2P Lending'
    },
    addCategory: 'Add a category',
    save: 'Save',
    addCategoryRowText: 'Add a new category',
    confirmAddAssetMainText: 'Your asset is saved',
    confirmAddAssetDescriptionText: 'You can review it on the Dashboard',
    done: 'Done',
    assetChartTitle: 'Distribution by Assets',
    categoryChartTitle: 'Distribution by Category',
    assetByAbsoluteValueChartTitle: 'Asset Values',
    categoryByAbsoluteValueChartTitle: 'Category Values',
    netWorth: 'Total Net Worth',
    dashboardMonthSelectorTitle: 'Select month',
    outdatedAssetText: '(tap to update)',
    quickUpdateAssetTitle: 'Amount for {{month}}',
    moreOptions: 'More Options',
    currentAmount: 'Currently {{amount}}',
    addHistoricDataButton: 'Add historic data',
    deleteAmount: 'Delete month data',
    growth1m: '1m Growth',
    growth1y: '1y Growth',
    welcomeToNewMonthTitle: 'Welcome to {{month}}',
    welcomeToNewMonthMessage: 'Tap here to update your assets and see the new outlook of your net worth',
    errorFetchingData: 'Cannot connect to server due to lack of connectivity. Your data may be outdated.',
    errorSavingData: 'There is a problem saving your data. Please try again later. '
  }
};
